# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-1tWlmIiPjIE6Q3Pq29hUcF2r_-Ipc_8
"""

from sklearn.preprocessing import OneHotEncoder
import pandas as pd

houseprices_db.drop(["ocean_proximity"], axis=1)
dataframe = pd.DataFrame(encoded_data, columns=new_feature)
houseprices_db = pd.concat([houseprices_db, dataframe], axis=1)
print(houseprices_db)

houseprices_db = pd.read_csv("houseprices_project_1.csv")
#Initialize the OneHotEncoder
OHE = OneHotEncoder(handle_unknown = "ignore", sparse=False)
#Transform data using module
encoded_data = OHE.fit_transform(houseprices_db[["ocean_proximity"]])
#print encoded data
print(encoded_data)
new_feature = OHE.get_feature_names_out(["ocean_proximity"])
print(new_feature)